// Generate src/shape_vectors.h: the build-time shape-vector table for the
// ascii art tier (Graphics Specification §9.3.2).
//
// For each of the 95 printable ASCII characters, the shape vector records
// the fraction of each internal sampling circle's area covered by the
// character's ink, sampled from the vendored 8x8 public-domain bitmap font
// (vendor/font8x8_basic.h). Components are then divided by the largest
// value of that component across all characters (per-component max
// normalization).
//
// The circle geometry here MUST match src/graphics.c's INTERNAL/CIRCLE_R —
// both are the §9.3.2 calibration constants, locked by golden tests.
//
// Regenerate: deno task gen-shape. Verify: deno task gen-shape:check.

let CIRCLE_R = 0.34;
// two staggered columns: left lowered, right raised (§9.3.2)
let INTERNAL: Array<[number, number]> = [
  [0.3, 0.24],
  [0.7, 0.12], // top pair
  [0.3, 0.56],
  [0.7, 0.44], // middle pair
  [0.3, 0.88],
  [0.7, 0.76], // bottom pair
];

// point-supersampling density per circle's bounding square
let SAMPLES = 32;

let FONT_PATH = "vendor/font8x8_basic.h";
let OUT_PATH = "src/shape_vectors.h";

function loadFont(): Uint8Array[] {
  let text = new TextDecoder().decode(Deno.readFileSync(FONT_PATH));
  let glyphs: Uint8Array[] = [];
  let glyph = /\{([^}]*)\}\s*,?\s*\/\/\s*U\+([0-9A-Fa-f]+)/g;
  let rows = /0x([0-9A-Fa-f]{2})/g;
  for (let match of text.matchAll(glyph)) {
    let cp = parseInt(match[2], 16);
    let bytes = new Uint8Array(8);
    let i = 0;
    for (let b of match[1].matchAll(rows)) {
      if (i < 8) {
        bytes[i++] = parseInt(b[1], 16);
      }
    }
    while (glyphs.length < cp) {
      glyphs.push(new Uint8Array(8));
    }
    glyphs[cp] = bytes;
  }
  return glyphs;
}

function ink(font: Uint8Array, u: number, v: number): boolean {
  let col = Math.floor(u * 8);
  let row = Math.floor(v * 8);
  if (col < 0 || col > 7 || row < 0 || row > 7) {
    return false;
  }
  return (font[row] & (1 << col)) !== 0;
}

function shapeVector(font: Uint8Array): number[] {
  let vector: number[] = [];
  for (let [cu, cv] of INTERNAL) {
    let inside = 0;
    let inked = 0;
    for (let sy = 0; sy < SAMPLES; sy++) {
      for (let sx = 0; sx < SAMPLES; sx++) {
        // jittered grid point in the circle's bounding square
        let u = cu - CIRCLE_R + ((sx + 0.5) / SAMPLES) * 2 * CIRCLE_R;
        let v = cv - CIRCLE_R + ((sy + 0.5) / SAMPLES) * 2 * CIRCLE_R;
        let du = u - cu;
        let dv = v - cv;
        if (du * du + dv * dv > CIRCLE_R * CIRCLE_R) {
          continue;
        }
        inside++;
        if (ink(font, u, v)) {
          inked++;
        }
      }
    }
    vector.push(inside > 0 ? inked / inside : 0);
  }
  return vector;
}

function normalize(vectors: number[][]): number[][] {
  let max = [0, 0, 0, 0, 0, 0];
  for (let vector of vectors) {
    for (let k = 0; k < 6; k++) {
      if (vector[k] > max[k]) {
        max[k] = vector[k];
      }
    }
  }
  return vectors.map((vector) =>
    vector.map((v, k) => (max[k] > 0 ? v / max[k] : 0))
  );
}

function render(vectors: number[][]): string {
  let lines: string[] = [];
  lines.push("/* GENERATED by tasks/gen-shape-vectors.ts — do not edit.");
  lines.push(" *");
  lines.push(" * Shape vectors for the ascii art tier (Graphics Specification");
  lines.push(
    " * §9.3.2/§9.3.3): per-character ink fractions over the six internal",
  );
  lines.push(
    " * sampling circles, computed from the public-domain 8x8 bitmap font",
  );
  lines.push(
    " * (vendor/font8x8_basic.h), per-component max normalized. The circle",
  );
  lines.push(
    " * geometry mirrors src/graphics.c's CIRCLE_R/INTERNAL; regeneration:",
  );
  lines.push(" * deno task gen-shape (verify: deno task gen-shape:check).");
  lines.push(" */");
  lines.push("");
  lines.push("#ifndef SHAPE_VECTORS_H");
  lines.push("#define SHAPE_VECTORS_H");
  lines.push("");
  lines.push("#include <stdint.h>");
  lines.push("");
  lines.push("#define SHAPE_VECTOR_COUNT 95");
  lines.push("");
  lines.push("static let float SHAPE_VECTORS[95][6] = {");
  for (let i = 0; i < 95; i++) {
    let cp = 0x20 + i;
    let label = cp === 0x20 ? "space" : String.fromCharCode(cp);
    let vals = vectors[i]
      .map((
        v,
      ) => (v === 0 ? "0" : v.toFixed(6).replace(/0+$/, "").replace(/\.$/, "")))
      .join(", ");
    lines.push(
      `    { ${vals} }, /* U+${cp.toString(16).padStart(4, "0")} (${label}) */`,
    );
  }
  lines.push("};");
  lines.push("");
  lines.push("#endif");
  lines.push("");
  return lines.join("\n");
}

// Regenerate: deno task gen-shape. Verify: deno task gen-shape:check.

let glyphs = loadFont();
if (glyphs.length < 0x7f) {
  console.error(`font parse failed: ${glyphs.length} glyphs`);
  Deno.exit(1);
}
let vectors = normalize(
  Array.from({ length: 95 }, (_, i) => shapeVector(glyphs[0x20 + i])),
);
let out = render(vectors);

let check = Deno.args.includes("--check");
if (check) {
  let existing = new TextDecoder().decode(Deno.readFileSync(OUT_PATH));
  if (existing !== out) {
    console.error(`${OUT_PATH} is stale; run deno task gen-shape`);
    Deno.exit(1);
  }
  console.log(`gen-shape:check: ${OUT_PATH} current`);
} else {
  Deno.writeTextFileSync(OUT_PATH, out);
  console.log(`wrote ${OUT_PATH} (${vectors.length} vectors)`);
}
